config/routes.rb
Rails.application.routes.draw do
  resources :scafrocks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scafrock.rb
class Scafrock < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/scafrocks_controller.rb
class ScafrocksController < ApplicationController
  before_action :set_scafrock, only: [:show, :edit, :update, :destroy]
  before_action :getparams, only: [:new, :edit]

  # GET /scafrocks
  # GET /scafrocks.json
  def index
    @scafrocks = Scafrock.all
  end

  # GET /scafrocks/1
  # GET /scafrocks/1.json
  def show
    unless (1..3) === @scafrock.hand_a and (1..3) === @scafrock.hand_b
      redirect_to(scafrocks_path, notice: 'Please wait until all players complete.')
    end
    
  	@img_fname = [nil, 'r', 's', 'p']
		@result = ['Draw', 'Win!', 'Lose...']
		@numresult = [0, 0]
		if @scafrock.hand_a == @scafrock.hand_b and @scafrock.hand_a != nil
			@numresult = [0, 0]
		elsif (@scafrock.hand_a == 1 and @scafrock.hand_b == 2) or (@scafrock.hand_a == 2 and @scafrock.hand_b == 3) or (@scafrock.hand_a == 3 and @scafrock.hand_b == 1)
			@numresult = [1, 2]
		elsif (@scafrock.hand_a == 1 and @scafrock.hand_b == 3) or (@scafrock.hand_a == 2 and @scafrock.hand_b == 1) or (@scafrock.hand_a == 3 and @scafrock.hand_b == 2)
			@numresult = [2, 1]
		else
			@numresult = [0, 0]
		end
  end

  # GET /scafrocks/new
  def new
    @scafrock = Scafrock.new
    if @scafrock.save
      redirect_to(edit_scafrock_path(@scafrock, player: 'a'), notice: 'New game has started.')
    end
  end

  # GET /scafrocks/1/edit
  def edit
	end

	# POST /scafrocks
  # POST /scafrocks.json
  def create
    @scafrock = Scafrock.new(scafrock_params)

    respond_to do |format|
      if @scafrock.save
        format.html { redirect_to scafrocks_path, notice: 'New game was successfully created.' }
        format.json { render :show, status: :created, location: @scafrock }
      else
        format.html { render :new }
        format.json { render json: @scafrock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scafrocks/1
  # PATCH/PUT /scafrocks/1.json
  def update
    respond_to do |format|
      if @scafrock.update(scafrock_params)
        format.html { redirect_to @scafrock, notice: "Scafrock was successfully updated." }
        format.json { render :show, status: :ok, location: @scafrock }
      else
        format.html { render :edit }
        format.json { render json: @scafrock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scafrocks/1
  # DELETE /scafrocks/1.json
  def destroy
    @scafrock.destroy
    respond_to do |format|
      format.html { redirect_to scafrocks_url, notice: 'Scafrock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scafrock
      @scafrock = Scafrock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scafrock_params
      params.require(:scafrock).permit(:name_a, :hand_a, :name_b, :hand_b)
    end

    def getparams
      @sw = params[:player]
      unless @sw == 'a' or @sw == 'b'
        @label_name = 'invalid params'
		  end
      @label_name = "Player #{@sw}"
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scafrocks_helper.rb
module ScafrocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scafrocks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scafrocks/_form.html.erb
<%= form_for(scafrock) do |f| %>
  <% if scafrock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scafrock.errors.count, "error") %> prohibited this scafrock from being saved:</h2>

      <ul>
      <% scafrock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
		<%= f.label "#{@label_name}" %>
		<%= f.text_field "name_#{@sw}" %>
  </div>

	<div class="field", style="float:left">
		<%= f.label "Hand for #{@label_name}" %>
		<%= f.radio_button "hand_#{@sw}", 1 %><img onClick="handleImageClick('<%= "#{@sw}_1" %>');" src="<%= asset_path "r.png" %>" width="64" height="64">
		<%= f.radio_button "hand_#{@sw}", 2 %><img onClick="handleImageClick('<%= "#{@sw}_2" %>');" src="<%= asset_path "s.png" %>" width="64" height="64">
		<%= f.radio_button "hand_#{@sw}", 3 %><img onClick="handleImageClick('<%= "#{@sw}_3" %>');" src="<%= asset_path "p.png" %>" width="64" height="64">
	</div>

	<div class = "actions", style="clear:both">
		<%= f.submit 'Submit' %>
	</div>

<script>
    function handleImageClick(id) {

			console.log("I got an event. ", id);
      var el_id = 'scafrock_hand_' + id;
			document.getElementById(el_id).checked=true;
     

		};

</script>

<% end %>

app/views/scafrocks/edit.html.erb
<h1>Editing Scafrock</h1>

<%= render 'form', scafrock: @scafrock %>

<%= link_to 'Show', @scafrock %> |
<%= link_to 'Back', scafrocks_path %>

app/views/scafrocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Janken!</h1>

<table>
  <thead>
    <tr>
      <th>Name a</th>
      <th> </th>
      <th>Name b</th>
      <th> </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scafrocks.each do |scafrock| %>
      <tr>
        <td><%= scafrock.name_a %></td>
        <td><%= link_to 'Play A', edit_scafrock_path(scafrock, player: 'a') %></td>
        <td><%= scafrock.name_b %></td>
        <td><%= link_to 'Play B', edit_scafrock_path(scafrock, player: 'b') %></td>
  	  	<td><%= link_to 'Show', scafrock, data: 1 %></td> 
        <td><%= link_to 'Destroy', scafrock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_scafrock_path(player: 'a') %>

app/views/scafrocks/new.html.erb
<h1>New Game</h1>

<%= render 'form', scafrock: @scafrock %>

<%= link_to 'Back', scafrocks_path %>

app/views/scafrocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @scafrock.name_a %>
</p>

<p>
	<%= image_tag("#{@img_fname[@scafrock.hand_a]}.png", :size => "64x64" ) %>
</p>

<p>
	<%= @result[@numresult[0]] %>
</p>

<p>
  <%= @scafrock.name_b %>
</p>

<p>
	<%= image_tag("#{@img_fname[@scafrock.hand_b]}.png", :size => "64x64" ) %>
</p>

<p>
	<%= @result[@numresult[1]] %>
</p>


<%= link_to 'Edit', edit_scafrock_path(@scafrock) %> |
<%= link_to 'Back', scafrocks_path %>